FROM node:22.14.0

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y git

RUN git clone https://www.github.com/planet-nine-app/addie.git addie
RUN git clone https://www.github.com/planet-nine-app/aretha.git aretha
RUN git clone https://www.github.com/planet-nine-app/bdo.git bdo
RUN git clone https://www.github.com/planet-nine-app/continuebee.git continuebee
RUN git clone https://www.github.com/planet-nine-app/dolores.git dolores
RUN git clone https://www.github.com/planet-nine-app/fount.git fount
RUN git clone https://www.github.com/planet-nine-app/joan.git joan
RUN git clone https://www.github.com/planet-nine-app/julia.git julia
RUN git clone https://www.github.com/planet-nine-app/minnie.git minnie
RUN git clone https://www.github.com/planet-nine-app/pref.git pref
RUN git clone https://www.github.com/planet-nine-app/sanora.git sanora
RUN git clone https://www.github.com/planet-nine-app/covenant.git covenant

# Clone prof (optional service) - clone from GitHub if available, skip if not
RUN git clone https://www.github.com/planet-nine-app/prof.git prof || echo "Prof service not available, skipping..."

# Clone the-advancement for Glyphenge
RUN git clone https://www.github.com/planet-nine-app/the-advancement.git the-advancement

# Expose all possible ports for 3 bases (40xx, 50xx, 60xx ranges)
# Base 1 (40xx)
EXPOSE 4000 4001 4002 4003 4004 4005 4006 4007 4008 4010 4011 4333
EXPOSE 4525 6277 6243
# Base 2 (50xx)
EXPOSE 5000 5001 5002 5003 5004 5005 5006 5007 5008 5010 5011 5333
EXPOSE 5525 8277 8243
# Base 3 (60xx)
EXPOSE 6000 6001 6002 6003 6004 6005 6006 6007 6008 6010 6011 6333
EXPOSE 6525 10277 10243
# Default ports (including prof on 3008, wiki on 3333, glyphenge on 3010)
EXPOSE 2525 2999 3000 3001 3002 3003 3004 3005 3006 3007 3008 3010 3011 3333 7243 7277

RUN npm install -g pm2
RUN npm install -g wiki
RUN npm install -g wiki-security-sessionless

# Clone allyabase for startup scripts and wiki plugin
RUN git clone https://www.github.com/planet-nine-app/allyabase.git allyabase

# Install wiki-plugin-allyabase dependencies from local clone
WORKDIR /usr/src/app/allyabase/src/wiki/wiki-plugin-allyabase
RUN npm install

# Install wiki-plugin-allyabase into wiki's node_modules from local clone
WORKDIR /usr/src/app
RUN WIKI_PATH=$(npm root -g)/wiki/node_modules && \
    mkdir -p "$WIKI_PATH" && \
    cp -r /usr/src/app/allyabase/src/wiki/wiki-plugin-allyabase "$WIKI_PATH/"

# Install wiki-plugin-home from local source
COPY third-party/wiki-plugin-home /usr/src/app/wiki-plugin-home
WORKDIR /usr/src/app/wiki-plugin-home
RUN npm install
WORKDIR /usr/src/app
RUN WIKI_PATH=$(npm root -g)/wiki/node_modules && \
    cp -r /usr/src/app/wiki-plugin-home "$WIKI_PATH/"

WORKDIR /usr/src/app/julia/src/server/node
RUN npm install

WORKDIR /usr/src/app/continuebee/src/server/node
RUN npm install

WORKDIR /usr/src/app/joan/src/server/node
RUN npm install

WORKDIR /usr/src/app/pref/src/server/node
RUN npm install

WORKDIR /usr/src/app/bdo/src/server/node
RUN npm install

WORKDIR /usr/src/app/dolores/src/server/node
RUN npm install

WORKDIR /usr/src/app/fount/src/server/node
RUN npm install

WORKDIR /usr/src/app/addie/src/server/node
RUN npm install

WORKDIR /usr/src/app/aretha/src/server/node
RUN npm install

WORKDIR /usr/src/app/sanora/src/server/node
RUN npm install

WORKDIR /usr/src/app/minnie/src/server/node
RUN npm install

WORKDIR /usr/src/app/covenant/src/server/node
RUN npm install

# Install prof dependencies if prof was cloned successfully
RUN if [ -d "/usr/src/app/prof/src/server/node" ]; then \
        cd /usr/src/app/prof/src/server/node && npm install; \
    else \
        echo "Prof not available, skipping npm install"; \
    fi

# Install Glyphenge dependencies
WORKDIR /usr/src/app/the-advancement/glyphenge
RUN npm install

# Install proxy server dependencies
WORKDIR /usr/src/app/allyabase/deployment/docker
RUN npm install
RUN npm install http-proxy

WORKDIR /usr/src/app

# Copy scripts for flexible port management and proxy server
COPY allyabase/deployment/docker/start-with-ports.sh /usr/src/app/
COPY allyabase/deployment/docker/update-service-ports.sh /usr/src/app/
COPY allyabase/deployment/docker/proxy-server.js /usr/src/app/allyabase/deployment/docker/
RUN chmod +x /usr/src/app/start-with-ports.sh
RUN chmod +x /usr/src/app/update-service-ports.sh

# Update service ports to use environment variables
RUN ./update-service-ports.sh

ENV PM2_SAVE_INTERVAL=30000
ENV PM2_LOG_DATE_FORMAT="YYYY-MM-DD HH:mm:ss.SSS"

# Default to no port offset (standard ports)
ENV PORT_OFFSET=0

CMD ["./start-with-ports.sh"]